services:

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: credit_system
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  discovery-server:
    build: ./discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    networks:
      - backend-network

  user-service:
    build: ./user-service
    container_name: user-service-container
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://mysql:3306/credit_system
      DB_USERNAME: root
      DB_PASSWORD: root
      JWT_SECRET: myverystrongjwtsecretkeyforhs256algorithm123456789
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka
    depends_on:
      mysql:
        condition: service_healthy
      discovery-server:
        condition: service_started
    networks:
      - backend-network
  data-collection-service:
    build: ./data-collection-service
    container_name: data-collection-service
    ports:
      - "8081:8081"
    environment:
      DB_URL: jdbc:mysql://mysql:3306/credit_system
      DB_USERNAME: root
      DB_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka
    depends_on:
      mysql:
        condition: service_healthy
      discovery-server:
        condition: service_started
    networks:
      - backend-network
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8085:8085"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka
    depends_on:
      - discovery-server
      - user-service
    networks:
      - backend-network
  score-service:
    build: ./score-service
    container_name: score-service
    ports:
      - "8082:8082"

    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka

    depends_on:
      mysql:
        condition: service_healthy
      discovery-server:
        condition: service_started

    networks:
      - backend-network
networks:
  backend-network:

volumes:
  mysql-data: