server:
  port: 8080

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/credit_system
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: my-super-secret-key-which-is-long-enough-123456
  access-token-expiration: 900000
  refresh-token-expiration: 7